#!/bin/bash
# Simulate a problematic token script that outputs empty lines and debugging info
# This is what was causing the concatenation to corrupt the token

# Empty line at start
echo ""

# Some debug output that should be ignored
# (some scripts might output this by accident)

# The actual token (long JWT)
echo "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEyMzQ1Njc4OTAifQ.eyJpc3MiOiJodHRwczovL2F1dGguc29tZWFwaS5jb20iLCJzdWIiOiJ1c2VyMTIzNDUiLCJhdWQiOiJodHRwczovL2FwaS5zb21lYXBpLmNvbSIsImV4cCI6MTczNTEwMDAwMCwiaWF0IjoxNzM1MDk2NDAwLCJuYmYiOjE3MzUwOTY0MDAsImp0aSI6ImFiY2RlZmdoLWlqa2xtbm9wLXFyc3R1dnd4LXl6MTIzNDU2Iiwic2NvcGVzIjpbInJlYWQiLCJ3cml0ZSIsImFkbWluIl0sInJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJ0ZW5hbnRfaWQiOiJ0ZW5hbnQtMTIzNDUiLCJ1c2VyX2lkIjoidXNlci0xMjM0NSIsInVzZXJuYW1lIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIn0.VGhpcyBpcyBhIHNpbXVsYXRlZCBzaWduYXR1cmUgdGhhdCB3b3VsZCBub3JtYWxseSBiZSBtdWNoIGxvbmdlciBhbmQgY29udGFpbiBjcnlwdG9ncmFwaGljIGRhdGEgZnJvbSB0aGUgUlNBIHNpZ25pbmcgcHJvY2VzcyB3aGljaCBtYWtlcyB0aGUgdG9rZW4gc2VjdXJlIGFuZCB2ZXJpZmlhYmxlIGJ5IHRoZSBBUEkgc2VydmVyLiBUaGlzIGlzIGp1c3QgYSBwbGFjZWhvbGRlci4"

# Trailing empty lines that might be there
echo ""