//! R13 slice 1 — the evaluator matrix.
//!
//! The engine has two evaluators for the same expression tree, and they do not
//! share rules (docs/ENGINE_REFACTORING.md § R13):
//!
//! - `RecursiveWhereEvaluator` — predicate → `Trilean`, serves `WHERE`.
//! - `ArithmeticEvaluator` — expression → `DataValue`, serves `SELECT`,
//!   `HAVING`, join conditions and, since P46, WHERE operands.
//!
//! This runs every predicate below through **both**, on every row of a table
//! built so that each operand is NULL somewhere, and compares each answer with
//! the three-valued SQL result. The expected strings were produced by DuckDB
//! (the parity reference), not derived by hand — see `EXPECTED`.
//!
//! The contract is the same as the parity corpus: a divergence is *recorded*,
//! with what we actually return, in `KNOWN`. The test fails if an unrecorded
//! divergence appears **or** if a recorded one changes — including being fixed,
//! so R13 slice 2 has to update this file to prove what it moved.
//!
//! Reading a row string: one character per table row, in row order.
//! `T`/`F`/`U` are TRUE/FALSE/UNKNOWN (NULL); `E` means the evaluator errored,
//! and `V` means the value evaluator returned a non-boolean, non-NULL value.

use sql_cli::data::arithmetic_evaluator::ArithmeticEvaluator;
use sql_cli::data::datatable::{DataColumn, DataRow, DataTable, DataValue};
use sql_cli::data::query_engine::QueryEngine;
use sql_cli::data::recursive_where_evaluator::RecursiveWhereEvaluator;
use sql_cli::data::trilean::Trilean;
use sql_cli::sql::parser::ast::SelectItem;
use sql_cli::sql::recursive_parser::Parser;
use std::sync::Arc;

/// Rows chosen so every binary shape sees a non-NULL pair both ways round, NULL
/// on the left, NULL on the right, and NULL on both.
///
/// | row | a    | b    | s     |
/// |-----|------|------|-------|
/// | 0   | 1    | 2    | 'abc' |
/// | 1   | 2    | 1    | 'xyz' |
/// | 2   | NULL | 1    | NULL  |
/// | 3   | 1    | NULL | 'abc' |
/// | 4   | NULL | NULL | NULL  |
fn table() -> DataTable {
    let mut t = DataTable::new("t");
    t.add_column(DataColumn::new("a"));
    t.add_column(DataColumn::new("b"));
    t.add_column(DataColumn::new("s"));
    let int = |v: Option<i64>| v.map_or(DataValue::Null, DataValue::Integer);
    let text = |v: Option<&str>| v.map_or(DataValue::Null, |s| DataValue::String(s.to_string()));
    for (a, b, s) in [
        (Some(1), Some(2), Some("abc")),
        (Some(2), Some(1), Some("xyz")),
        (None, Some(1), None),
        (Some(1), None, Some("abc")),
        (None, None, None),
    ] {
        t.add_row(DataRow::new(vec![int(a), int(b), text(s)]))
            .unwrap();
    }
    t
}

const ROWS: usize = 5;

/// `(predicate, SQL answer per row)`, generated by DuckDB from the same table:
/// `SELECT CASE WHEN (p) IS NULL THEN 'U' WHEN (p) THEN 'T' ELSE 'F' END`.
const EXPECTED: &[(&str, &str)] = &[
    // Comparisons, with NULL on each side.
    ("a < b", "TFUUU"),
    ("a = b", "FFUUU"),
    ("a <> b", "TTUUU"),
    ("a >= b", "FTUUU"),
    ("a = 1", "TFUTU"),
    ("1 < b", "TFFUU"),
    ("a = NULL", "UUUUU"),
    ("s = 'abc'", "TFUTU"),
    // NULL tests stay two-valued.
    ("a IS NULL", "FFTFT"),
    ("a IS NOT NULL", "TTFTF"),
    // Negation: NOT UNKNOWN is UNKNOWN.
    ("NOT (a < b)", "FTUUU"),
    ("NOT (a = 1)", "FTUFU"),
    // IN / NOT IN, NULL in the probe, in the list, and a column item.
    ("a IN (1, 3)", "TFUTU"),
    ("a IN (1, NULL)", "TUUTU"),
    ("a IN (b, 3)", "FFUUU"),
    ("a NOT IN (3, 4)", "TTUTU"),
    ("a NOT IN (1, NULL)", "FUUFU"),
    ("NOT (a IN (1, 3))", "FTUFU"),
    // BETWEEN, NULL in the value and in either bound.
    ("a BETWEEN 1 AND 5", "TTUTU"),
    ("a BETWEEN 1 AND b", "TFUUU"),
    ("a BETWEEN b AND 5", "FTUUU"),
    ("NOT (a BETWEEN 1 AND b)", "FTUUU"),
    // AND / OR: FALSE dominates AND, TRUE dominates OR, even over UNKNOWN.
    ("a > 0 AND b > 1", "TFFUU"),
    ("a > 1 OR b > 1", "TTUUU"),
    ("a > 5 AND b > 5", "FFFFU"),
    ("a > 5 OR b IS NULL", "FFUTT"),
    ("NOT (a > 0 AND b > 1)", "FTTUU"),
    ("NOT (a > 1 OR b > 1)", "FFUUU"),
    // LIKE.
    ("s LIKE 'a%'", "TFUTU"),
    ("NOT (s LIKE 'a%')", "FTUFU"),
    // Expression operands.
    ("a + 0 < b", "TFUUU"),
    ("a + b > 2", "TTUUU"),
    ("COALESCE(a, 0) < b", "TFTUU"),
    ("NOT (a + 0 < b)", "FTUUU"),
    // CASE: an UNKNOWN condition takes the ELSE branch.
    ("CASE WHEN a < b THEN 1 ELSE 0 END = 1", "TFFFF"),
    ("CASE WHEN a < b THEN true ELSE false END", "TFFFF"),
];

/// The same shapes under the engine's case-insensitive mode
/// (`--case-insensitive`), over the string column. DuckDB has no such mode, so
/// these were generated with each string comparison collated `NOCASE` (and
/// `LIKE` as `ILIKE`), e.g. `s COLLATE NOCASE < 'B'`.
const EXPECTED_CASE_INSENSITIVE: &[(&str, &str)] = &[
    ("s = 'ABC'", "TFUTU"),
    ("s <> 'ABC'", "FTUFU"),
    ("s < 'B'", "TFUTU"),
    ("s IN ('ABC', 'Q')", "TFUTU"),
    ("s NOT IN ('XYZ')", "TFUTU"),
    ("s BETWEEN 'ABC' AND 'M'", "TFUTU"),
    ("s LIKE 'A%'", "TFUTU"),
    ("NOT (s = 'ABC')", "FTUFU"),
    ("CASE WHEN s = 'ABC' THEN 1 ELSE 0 END = 1", "TFFTF"),
    ("UPPER(s) = 'abc'", "TFUTU"),
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Evaluator {
    /// `RecursiveWhereEvaluator`, as `WHERE <predicate>`.
    Where,
    /// `ArithmeticEvaluator`, as `SELECT (<predicate>) AS v`.
    Value,
}

/// A recorded divergence from `EXPECTED`: what this evaluator returns today,
/// and why. Remove an entry when a change makes the evaluator agree.
struct Known {
    evaluator: Evaluator,
    predicate: &'static str,
    observed: &'static str,
    why: &'static str,
}

// Empty since R13 slice 2 (2026-09-13), which made the value evaluator
// three-valued: all 32 value-evaluator entries recorded by slice 1 - comparisons
// (including NULL = NULL comparing equal), NOT, IN / NOT IN, BETWEEN, LIKE and
// AND / OR - went FIXED in one change, and the WHERE column did not move.
// Keep the mechanism: a new predicate that exposes a divergence is recorded
// here, with its finding, rather than left failing.
const KNOWN: &[Known] = &[];

// Recorded by R13 slice 3b (2026-09-14). The WHERE evaluator honours the
// engine's case-insensitive mode; the value evaluator has no such mode and
// always compares case-sensitively, so under `--case-insensitive` a SELECT,
// HAVING or CASE WHEN answers differently from the same predicate in WHERE.
const KNOWN_CASE_INSENSITIVE: &[Known] = &[
    Known {
        evaluator: Evaluator::Value,
        predicate: "s = 'ABC'",
        observed: "FFUFU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "s <> 'ABC'",
        observed: "TTUTU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "s < 'B'",
        observed: "FFUFU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "s IN ('ABC', 'Q')",
        observed: "FFUFU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "s NOT IN ('XYZ')",
        observed: "TTUTU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "s BETWEEN 'ABC' AND 'M'",
        observed: "FFUFU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "s LIKE 'A%'",
        observed: "FFUFU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "NOT (s = 'ABC')",
        observed: "TTUTU",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "CASE WHEN s = 'ABC' THEN 1 ELSE 0 END = 1",
        observed: "FFFFF",
        why: "WHERE hands CASE to an inner value evaluator built without the mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "CASE WHEN s = 'ABC' THEN 1 ELSE 0 END = 1",
        observed: "FFFFF",
        why: "value evaluator has no case-insensitive mode",
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "UPPER(s) = 'abc'",
        observed: "FFUFU",
        why: "value evaluator has no case-insensitive mode",
    },
];

fn trilean_char(t: Trilean) -> char {
    match t {
        Trilean::True => 'T',
        Trilean::False => 'F',
        Trilean::Unknown => 'U',
    }
}

fn observe_where(table: &DataTable, predicate: &str, case_insensitive: bool) -> String {
    let sql = format!("SELECT * FROM t WHERE {predicate}");
    let statement = Parser::new(&sql)
        .parse()
        .unwrap_or_else(|e| panic!("parse failed for {sql}: {e}"));
    let where_clause = statement.where_clause.expect("expected a WHERE clause");
    let mut evaluator = RecursiveWhereEvaluator::with_case_insensitive(table, case_insensitive);
    (0..ROWS)
        .map(|row| match evaluator.evaluate(&where_clause, row) {
            Ok(t) => trilean_char(t),
            Err(_) => 'E',
        })
        .collect()
}

fn observe_value(table: &DataTable, predicate: &str, case_insensitive: bool) -> String {
    // Parenthesised, because a bare `SELECT a AND b` does not parse (logged as
    // a parity gap of its own); the parentheses do not change the expression.
    let sql = format!("SELECT ({predicate}) AS v FROM t");
    let statement = Parser::new(&sql)
        .parse()
        .unwrap_or_else(|e| panic!("parse failed for {sql}: {e}"));
    let expr = match statement.select_items.first() {
        Some(SelectItem::Expression { expr, .. }) => expr.clone(),
        other => panic!("expected one expression select item for {sql}, got {other:?}"),
    };
    // No case-insensitive mode to ask for: see KNOWN_CASE_INSENSITIVE.
    let _ = case_insensitive;
    let mut evaluator = ArithmeticEvaluator::new(table);
    (0..ROWS)
        .map(|row| match evaluator.evaluate(&expr, row) {
            Ok(DataValue::Boolean(true)) => 'T',
            Ok(DataValue::Boolean(false)) => 'F',
            Ok(DataValue::Null) => 'U',
            Ok(_) => 'V',
            Err(_) => 'E',
        })
        .collect()
}

#[test]
fn every_predicate_through_both_evaluators() {
    check_matrix(EXPECTED, KNOWN, false);
}

#[test]
fn every_predicate_through_both_evaluators_case_insensitive() {
    check_matrix(EXPECTED_CASE_INSENSITIVE, KNOWN_CASE_INSENSITIVE, true);
}

fn check_matrix(expected_answers: &[(&str, &str)], known: &[Known], case_insensitive: bool) {
    let t = table();
    let mut problems = Vec::new();
    let mut matrix = Vec::new();

    for &(predicate, expected) in expected_answers {
        let where_got = observe_where(&t, predicate, case_insensitive);
        let value_got = observe_value(&t, predicate, case_insensitive);
        matrix.push(format!(
            "{predicate:<44} expected {expected}  where {where_got}  value {value_got}"
        ));

        for (evaluator, got) in [
            (Evaluator::Where, &where_got),
            (Evaluator::Value, &value_got),
        ] {
            let known = known
                .iter()
                .find(|k| k.evaluator == evaluator && k.predicate == predicate);
            match known {
                None if got != expected => problems.push(format!(
                    "UNRECORDED  {evaluator:?} `{predicate}`: expected {expected}, got {got}"
                )),
                Some(k) if k.observed == expected => problems.push(format!(
                    "STALE ENTRY {evaluator:?} `{predicate}`: KNOWN records the correct answer {expected}; remove it"
                )),
                Some(k) if got == expected => problems.push(format!(
                    "FIXED       {evaluator:?} `{predicate}` now agrees ({expected}); remove its KNOWN entry ({})",
                    k.why
                )),
                Some(k) if got != k.observed => problems.push(format!(
                    "CHANGED     {evaluator:?} `{predicate}`: KNOWN records {}, now {got} (expected {expected})",
                    k.observed
                )),
                _ => {}
            }
        }
    }

    // Every KNOWN entry must name a predicate that is still in the matrix.
    for k in known {
        if !expected_answers.iter().any(|(p, _)| *p == k.predicate) {
            problems.push(format!(
                "ORPHAN      {:?} `{}` is in KNOWN but not in EXPECTED",
                k.evaluator, k.predicate
            ));
        }
    }

    assert!(
        problems.is_empty(),
        "\n{}\n\nFull matrix:\n{}\n",
        problems.join("\n"),
        matrix.join("\n")
    );
}

/// Clause-level forms of the case-insensitive rows, run through
/// `QueryEngine::with_case_insensitive(true)`. The matrix above builds each
/// evaluator directly; these catch the engine's own construction sites (SELECT,
/// HAVING, aggregate arguments, WHERE operands), which is where the mode has to
/// be handed in. `(sql, DuckDB answer with s collated NOCASE, what we return
/// today if it differs)`. Rows are `|`-separated, cells `,`-separated.
const CLAUSES_CASE_INSENSITIVE: &[(&str, &str, Option<&str>)] = &[
    (
        "SELECT (s = 'ABC') AS v FROM t",
        "true|false|NULL|true|NULL",
        Some("false|false|NULL|false|NULL"),
    ),
    (
        "SELECT s, COUNT(*) AS n FROM t GROUP BY s HAVING s = 'ABC'",
        "abc,2",
        Some(""),
    ),
    (
        // Not COUNT(*): an empty ungrouped aggregate returns no row (P14).
        "SELECT a FROM t WHERE CASE WHEN s = 'ABC' THEN 1 ELSE 0 END = 1",
        "1|1",
        Some(""),
    ),
    (
        "SELECT SUM(CASE WHEN s = 'ABC' THEN 1 ELSE 0 END) AS n FROM t",
        "2",
        Some("0"),
    ),
    (
        "SELECT a, SUM(CASE WHEN s = 'ABC' THEN 1 ELSE 0 END) AS n FROM t \
         WHERE a IS NOT NULL GROUP BY a ORDER BY a",
        "1,2|2,0",
        Some("1,0|2,0"),
    ),
];

fn render(value: &DataValue) -> String {
    match value {
        DataValue::Null => "NULL".to_string(),
        DataValue::Boolean(b) => b.to_string(),
        DataValue::Integer(i) => i.to_string(),
        DataValue::Float(f) => f.to_string(),
        DataValue::String(s) => s.clone(),
        other => format!("{other:?}"),
    }
}

#[test]
fn clause_level_case_insensitive() {
    let engine = QueryEngine::with_case_insensitive(true);
    let t = Arc::new(table());
    let mut problems = Vec::new();

    for &(sql, expected, observed) in CLAUSES_CASE_INSENSITIVE {
        let got = match engine.execute(Arc::clone(&t), sql) {
            Ok(view) => (0..view.row_count())
                .map(|i| {
                    let row = view.get_row(i).expect("row in range");
                    row.values.iter().map(render).collect::<Vec<_>>().join(",")
                })
                .collect::<Vec<_>>()
                .join("|"),
            Err(e) => format!("ERROR: {e}"),
        };
        match observed {
            None if got != expected => problems.push(format!(
                "UNRECORDED  `{sql}`: expected {expected}, got {got}"
            )),
            Some(_) if got == expected => problems.push(format!(
                "FIXED       `{sql}` now agrees ({expected}); drop its observed answer"
            )),
            Some(o) if got != o => problems.push(format!(
                "CHANGED     `{sql}`: recorded {o}, now {got} (expected {expected})"
            )),
            _ => {}
        }
    }

    assert!(problems.is_empty(), "\n{}\n", problems.join("\n"));
}
