//! R13 slice 1 — the evaluator matrix.
//!
//! The engine has two evaluators for the same expression tree, and they do not
//! share rules (docs/ENGINE_REFACTORING.md § R13):
//!
//! - `RecursiveWhereEvaluator` — predicate → `Trilean`, serves `WHERE`.
//! - `ArithmeticEvaluator` — expression → `DataValue`, serves `SELECT`,
//!   `HAVING`, join conditions and, since P46, WHERE operands.
//!
//! This runs every predicate below through **both**, on every row of a table
//! built so that each operand is NULL somewhere, and compares each answer with
//! the three-valued SQL result. The expected strings were produced by DuckDB
//! (the parity reference), not derived by hand — see `EXPECTED`.
//!
//! The contract is the same as the parity corpus: a divergence is *recorded*,
//! with what we actually return, in `KNOWN`. The test fails if an unrecorded
//! divergence appears **or** if a recorded one changes — including being fixed,
//! so R13 slice 2 has to update this file to prove what it moved.
//!
//! Reading a row string: one character per table row, in row order.
//! `T`/`F`/`U` are TRUE/FALSE/UNKNOWN (NULL); `E` means the evaluator errored,
//! and `V` means the value evaluator returned a non-boolean, non-NULL value.

use sql_cli::data::arithmetic_evaluator::ArithmeticEvaluator;
use sql_cli::data::datatable::{DataColumn, DataRow, DataTable, DataValue};
use sql_cli::data::query_engine::QueryEngine;
use sql_cli::data::recursive_where_evaluator::RecursiveWhereEvaluator;
use sql_cli::data::trilean::Trilean;
use sql_cli::sql::parser::ast::SelectItem;
use sql_cli::sql::recursive_parser::Parser;
use std::sync::Arc;

/// Rows chosen so every binary shape sees a non-NULL pair both ways round, NULL
/// on the left, NULL on the right, and NULL on both.
///
/// | row | a    | b    | s     |
/// |-----|------|------|-------|
/// | 0   | 1    | 2    | 'abc' |
/// | 1   | 2    | 1    | 'xyz' |
/// | 2   | NULL | 1    | NULL  |
/// | 3   | 1    | NULL | 'abc' |
/// | 4   | NULL | NULL | NULL  |
fn table() -> DataTable {
    let mut t = DataTable::new("t");
    t.add_column(DataColumn::new("a"));
    t.add_column(DataColumn::new("b"));
    t.add_column(DataColumn::new("s"));
    let int = |v: Option<i64>| v.map_or(DataValue::Null, DataValue::Integer);
    let text = |v: Option<&str>| v.map_or(DataValue::Null, |s| DataValue::String(s.to_string()));
    for (a, b, s) in [
        (Some(1), Some(2), Some("abc")),
        (Some(2), Some(1), Some("xyz")),
        (None, Some(1), None),
        (Some(1), None, Some("abc")),
        (None, None, None),
    ] {
        t.add_row(DataRow::new(vec![int(a), int(b), text(s)]))
            .unwrap();
    }
    t
}

/// `(predicate, SQL answer per row)`, generated by DuckDB from the same table:
/// `SELECT CASE WHEN (p) IS NULL THEN 'U' WHEN (p) THEN 'T' ELSE 'F' END`.
const EXPECTED: &[(&str, &str)] = &[
    // Comparisons, with NULL on each side.
    ("a < b", "TFUUU"),
    ("a = b", "FFUUU"),
    ("a <> b", "TTUUU"),
    ("a >= b", "FTUUU"),
    ("a = 1", "TFUTU"),
    ("1 < b", "TFFUU"),
    ("a = NULL", "UUUUU"),
    ("s = 'abc'", "TFUTU"),
    // NULL tests stay two-valued.
    ("a IS NULL", "FFTFT"),
    ("a IS NOT NULL", "TTFTF"),
    // Negation: NOT UNKNOWN is UNKNOWN.
    ("NOT (a < b)", "FTUUU"),
    ("NOT (a = 1)", "FTUFU"),
    // IN / NOT IN, NULL in the probe, in the list, and a column item.
    ("a IN (1, 3)", "TFUTU"),
    ("a IN (1, NULL)", "TUUTU"),
    ("a IN (b, 3)", "FFUUU"),
    ("a NOT IN (3, 4)", "TTUTU"),
    ("a NOT IN (1, NULL)", "FUUFU"),
    ("NOT (a IN (1, 3))", "FTUFU"),
    // BETWEEN, NULL in the value and in either bound.
    ("a BETWEEN 1 AND 5", "TTUTU"),
    ("a BETWEEN 1 AND b", "TFUUU"),
    ("a BETWEEN b AND 5", "FTUUU"),
    ("NOT (a BETWEEN 1 AND b)", "FTUUU"),
    // AND / OR: FALSE dominates AND, TRUE dominates OR, even over UNKNOWN.
    ("a > 0 AND b > 1", "TFFUU"),
    ("a > 1 OR b > 1", "TTUUU"),
    ("a > 5 AND b > 5", "FFFFU"),
    ("a > 5 OR b IS NULL", "FFUTT"),
    ("NOT (a > 0 AND b > 1)", "FTTUU"),
    ("NOT (a > 1 OR b > 1)", "FFUUU"),
    // LIKE.
    ("s LIKE 'a%'", "TFUTU"),
    ("NOT (s LIKE 'a%')", "FTUFU"),
    // Expression operands.
    ("a + 0 < b", "TFUUU"),
    ("a + b > 2", "TTUUU"),
    ("COALESCE(a, 0) < b", "TFTUU"),
    ("NOT (a + 0 < b)", "FTUUU"),
    // CASE: an UNKNOWN condition takes the ELSE branch.
    ("CASE WHEN a < b THEN 1 ELSE 0 END = 1", "TFFFF"),
    ("CASE WHEN a < b THEN true ELSE false END", "TFFFF"),
];

/// The same shapes under the engine's case-insensitive mode
/// (`--case-insensitive`), over the string column. DuckDB has no such mode, so
/// these were generated with each string comparison collated `NOCASE` (and
/// `LIKE` as `ILIKE`), e.g. `s COLLATE NOCASE < 'B'`.
const EXPECTED_CASE_INSENSITIVE: &[(&str, &str)] = &[
    ("s = 'ABC'", "TFUTU"),
    ("s <> 'ABC'", "FTUFU"),
    ("s < 'B'", "TFUTU"),
    ("s IN ('ABC', 'Q')", "TFUTU"),
    ("s NOT IN ('XYZ')", "TFUTU"),
    ("s BETWEEN 'ABC' AND 'M'", "TFUTU"),
    ("s LIKE 'A%'", "TFUTU"),
    ("NOT (s = 'ABC')", "FTUFU"),
    ("CASE WHEN s = 'ABC' THEN 1 ELSE 0 END = 1", "TFFTF"),
    ("UPPER(s) = 'abc'", "TFUTU"),
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Evaluator {
    /// `RecursiveWhereEvaluator`, as `WHERE <predicate>`.
    Where,
    /// `ArithmeticEvaluator`, as `SELECT (<predicate>) AS v`.
    Value,
}

/// A recorded divergence from `EXPECTED`: what this evaluator returns today,
/// and why. Remove an entry when a change makes the evaluator agree.
struct Known {
    evaluator: Evaluator,
    predicate: &'static str,
    observed: &'static str,
    why: &'static str,
}

// Empty since R13 slice 2 (2026-09-13), which made the value evaluator
// three-valued: all 32 value-evaluator entries recorded by slice 1 - comparisons
// (including NULL = NULL comparing equal), NOT, IN / NOT IN, BETWEEN, LIKE and
// AND / OR - went FIXED in one change, and the WHERE column did not move.
// Keep the mechanism: a new predicate that exposes a divergence is recorded
// here, with its finding, rather than left failing.
const KNOWN: &[Known] = &[];

// Empty since R13 slice 3b (2026-09-14). Slice 3b recorded 11 divergences:
// the value evaluator had no case-insensitive mode, so every string predicate
// here compared case-sensitively outside WHERE - and inside WHERE under a CASE,
// which WHERE hands to an inner value evaluator. The mode is now handed in at
// every construction site, and all 11 went FIXED in one change.
const KNOWN_CASE_INSENSITIVE: &[Known] = &[];

/// The operand readers (R13 slice 4). The two evaluators turn a literal into a
/// value with their own code, so a predicate over the same column can compare
/// against two different values. These rows exercise the readers rather than
/// NULL logic: an integer beyond 2^53, where an `f64` round trip changes the
/// value, and numbers held as strings.
///
/// | row | big              | s     | n    |
/// |-----|------------------|-------|------|
/// | 0   | 9007199254740993 | '5.0' | 5.0  |
/// | 1   | 9007199254740992 | '5'   | NULL |
/// | 2   | NULL             | NULL  | 7.5  |
fn operand_table() -> DataTable {
    let mut t = DataTable::new("t");
    t.add_column(DataColumn::new("big"));
    t.add_column(DataColumn::new("s"));
    t.add_column(DataColumn::new("n"));
    let int = |v: Option<i64>| v.map_or(DataValue::Null, DataValue::Integer);
    let text = |v: Option<&str>| v.map_or(DataValue::Null, |s| DataValue::String(s.to_string()));
    let float = |v: Option<f64>| v.map_or(DataValue::Null, DataValue::Float);
    for (big, s, n) in [
        (Some(9_007_199_254_740_993), Some("5.0"), Some(5.0)),
        (Some(9_007_199_254_740_992), Some("5"), None),
        (None, None, Some(7.5)),
    ] {
        t.add_row(DataRow::new(vec![int(big), text(s), float(n)]))
            .unwrap();
    }
    t
}

/// Generated by DuckDB from the same table (`big BIGINT, s VARCHAR,
/// n DOUBLE`), as for `EXPECTED`.
const EXPECTED_OPERANDS: &[(&str, &str)] = &[
    // An integer literal beyond 2^53, both sides of each comparison.
    ("big = 9007199254740993", "TFU"),
    ("big <> 9007199254740993", "FTU"),
    ("big = 9007199254740992", "FTU"),
    ("9007199254740993 = big", "TFU"),
    ("big > 9007199254740992", "TFU"),
    ("big IN (9007199254740993, 1)", "TFU"),
    ("big BETWEEN 9007199254740993 AND 9007199254740994", "TFU"),
    // A number held as a string, against an integer and a decimal literal.
    ("s = 5.0", "TTU"),
    ("s = 5", "TTU"),
    // A float column against integer and decimal literals.
    ("n = 5", "TUF"),
    ("n = 7.5", "FUT"),
    ("n > 7", "FUT"),
];

const STRING_VS_INTEGER: &str = "P53: '5.0' = 5 compares as text in both evaluators; DuckDB casts \
     the string to the number";

// R13 slice 4 recorded four WHERE entries here - three from P54 (an integer
// literal beyond 2^53 rounded through f64) and `s = 5.0` (5.0 read as Integer
// 5). All four went FIXED when WHERE's comparisons started delegating to the
// value evaluator, whose reader was already right. P53 is in both evaluators.
const KNOWN_OPERANDS: &[Known] = &[
    Known {
        evaluator: Evaluator::Where,
        predicate: "s = 5",
        observed: "FTU",
        why: STRING_VS_INTEGER,
    },
    Known {
        evaluator: Evaluator::Value,
        predicate: "s = 5",
        observed: "FTU",
        why: STRING_VS_INTEGER,
    },
];

/// LIKE (R13 slice 4). WHERE and the value evaluator each have their own
/// matcher - WHERE a regex built from the pattern, the value evaluator a
/// character walk - so these rows aim at what separates the two: pattern
/// characters that mean something to a regex, and text across a newline.
///
/// | row | s               |
/// |-----|-----------------|
/// | 0   | 'abc'           |
/// | 1   | 'a.c'           |
/// | 2   | 'a(bc'          |
/// | 3   | 'line1\nline2'  |
/// | 4   | NULL            |
/// | 5   | 'ABC'           |
/// | 6   | '[a]bc'         |
fn like_table() -> DataTable {
    let mut t = DataTable::new("t");
    t.add_column(DataColumn::new("s"));
    for s in [
        Some("abc"),
        Some("a.c"),
        Some("a(bc"),
        Some("line1\nline2"),
        None,
        Some("ABC"),
        Some("[a]bc"),
    ] {
        let v = s.map_or(DataValue::Null, |s| DataValue::String(s.to_string()));
        t.add_row(DataRow::new(vec![v])).unwrap();
    }
    t
}

/// Generated by DuckDB from the same table (`s VARCHAR`), as for `EXPECTED`.
const EXPECTED_LIKE: &[(&str, &str)] = &[
    // Characters that are syntax to a regex are literal in a LIKE pattern.
    ("s LIKE 'a.c'", "FTFFUFF"),
    ("s LIKE 'a(b%'", "FFTFUFF"),
    ("s LIKE '[a]bc'", "FFFFUFT"),
    // `%` and `_` are the only wildcards, and `%` spans a newline.
    ("s LIKE 'a_c'", "TTFFUFF"),
    ("s LIKE '%'", "TTTTUTT"),
    ("s LIKE 'line1%'", "FFFTUFF"),
    ("s LIKE '%2'", "FFFTUFF"),
    // Anchored at both ends, and case-sensitive outside --case-insensitive.
    ("s LIKE 'abc'", "TFFFUFF"),
    ("s LIKE 'A%'", "FFFFUTF"),
    ("s LIKE ''", "FFFFUFF"),
];

/// LIKE over a number, on the operand table. DuckDB refuses these outright
/// (no `LIKE(DOUBLE, VARCHAR)`), so the expected answers are **not** DuckDB's:
/// they are the deliberate choice recorded as D2 in docs/SQL_PARITY.md - a
/// number is matched as the text the tool displays for it. `5.0` displays as
/// `5`, so it matches `'5%'` but not `'5.0'`.
const EXPECTED_NUMBER_LIKE: &[(&str, &str)] = &[
    ("n LIKE '5%'", "TUF"),
    ("n LIKE '5.0'", "FUF"),
    ("n LIKE '7._'", "FUT"),
    ("big LIKE '9007%'", "TTU"),
    ("big LIKE '%993'", "TFU"),
];

// R13 slice 4 recorded four WHERE entries here - WHERE's LIKE answered FALSE
// for every non-text operand. All four went FIXED when LIKE delegated.
const KNOWN_NUMBER_LIKE: &[Known] = &[];

// R13 slice 4 recorded six WHERE entries here (P55: the pattern compiled to a
// regex, unescaped - `.`, `[a]` and `(` were live, and `%` stopped at a
// newline). All six went FIXED when LIKE delegated to `sql_like`.
const KNOWN_LIKE: &[Known] = &[];

/// Method calls (R13 slice 5). WHERE has its own `Contains` / `StartsWith` /
/// `EndsWith` and its own left-side `Length` / `IndexOf` / `Trim*`; the value
/// evaluator maps the same methods onto registry functions. The methods are
/// ours, not SQL, so each expected answer comes from DuckDB running the
/// function it corresponds to: `contains`, `starts_with`, `ends_with`,
/// `length`, `instr(s, x) - 1` (IndexOf is 0-based, -1 when absent), `trim`,
/// `ltrim`, `rtrim`.
///
/// | row | s      | n    |
/// |-----|--------|------|
/// | 0   | 'abc'  | 5    |
/// | 1   | 'ABC'  | 12   |
/// | 2   | NULL   | NULL |
/// | 3   | ' aB ' | 7.5  |
fn method_table() -> DataTable {
    let mut t = DataTable::new("t");
    t.add_column(DataColumn::new("s"));
    t.add_column(DataColumn::new("n"));
    let text = |v: Option<&str>| v.map_or(DataValue::Null, |s| DataValue::String(s.to_string()));
    for (s, n) in [
        (Some("abc"), DataValue::Integer(5)),
        (Some("ABC"), DataValue::Integer(12)),
        (None, DataValue::Null),
        (Some(" aB "), DataValue::Float(7.5)),
    ] {
        t.add_row(DataRow::new(vec![text(s), n])).unwrap();
    }
    t
}

/// Generated by DuckDB from the same table, as for `EXPECTED`.
const EXPECTED_METHODS: &[(&str, &str)] = &[
    // Case-sensitive outside --case-insensitive, like every other comparison
    // (D3), and NULL for a NULL receiver - so NOT does not select it (P56).
    ("s.Contains('b')", "TFUF"),
    ("s.Contains('B')", "FTUT"),
    ("NOT s.Contains('b')", "FTUT"),
    ("s.StartsWith('a')", "TFUF"),
    ("s.EndsWith('C')", "FTUF"),
    // Value-returning methods, on the left of a comparison.
    ("s.Length() > 3", "FFUT"),
    ("s.IndexOf('b') = 1", "TFUF"),
    ("s.IndexOf('z') = -1", "TTUT"),
    ("s.Trim() = 'aB'", "FFUT"),
    ("s.TrimStart() = 'aB '", "FFUT"),
    ("s.TrimEnd() = ' aB'", "FFUT"),
    // Any other method on the left of a comparison, and a qualified receiver.
    ("s.ToUpper() = 'ABC'", "TTUF"),
    ("s.Replace('a', 'z') = 'zbc'", "TFUF"),
    ("t.s.Contains('b')", "TFUF"),
    // The function forms share the method's implementation and its rules.
    ("CONTAINS(s, 'B')", "FTUT"),
    ("INSTR(s, 'b') = 2", "TFUF"),
    ("CONTAINS(s, NULL)", "UUUU"),
];

/// The same methods under `--case-insensitive`. DuckDB has no such mode; the
/// answers are DuckDB's over `lower(s)` (and `COLLATE NOCASE` for `=`), the
/// same derivation as `EXPECTED_CASE_INSENSITIVE`. D3: a method's search
/// follows the switch exactly as `=` and LIKE do.
const EXPECTED_METHODS_CASE_INSENSITIVE: &[(&str, &str)] = &[
    ("s.Contains('B')", "TTUT"),
    ("NOT s.Contains('B')", "FFUF"),
    ("s.StartsWith('A')", "TTUF"),
    ("s.EndsWith('c')", "TTUF"),
    ("s.IndexOf('B') = 1", "TTUF"),
    ("s.Trim() = 'AB'", "FFUT"),
    ("CONTAINS(s, 'b')", "TTUT"),
    ("INSTR(s, 'b') = 2", "TTUF"),
    ("ENDSWITH(s, 'c')", "TTUF"),
];

/// A method over a number. DuckDB refuses these (no implicit cast to VARCHAR),
/// so the expected answers are the D2 rule extended to methods: a number is
/// read as the text sql-cli displays for it (`5`, `12`, `7.5`).
const EXPECTED_NUMBER_METHODS: &[(&str, &str)] = &[
    ("n.Contains('5')", "TFUT"),
    ("n.StartsWith('1')", "FTUF"),
    ("n.Length() > 1", "FTUT"),
    ("INSTR(n, '5') = 1", "TFUF"),
    ("CONTAINS(n, '.')", "FFUT"),
];

// Recorded by R13 slice 5's pin (2026-09-26), grouped by fault; an observed
// string can combine two. The pin also recorded 27 value-evaluator and
// function-form entries - the registry's search functions answered FALSE for
// NULL, ignored --case-insensitive and rejected a number - which all went FIXED
// when those functions moved onto one `search_text` reader. What is left is
// WHERE's own method-call arms, which go when WHERE delegates method calls.
const NULL_RECEIVER: &str = "P56: WHERE's method over a NULL receiver answers FALSE (its Length /      IndexOf / Trim* a non-NULL value) instead of NULL";
const NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE: &str =
    "P56 (NULL receiver answers FALSE) and D3 (WHERE's search methods always ignore case)";
const WHERE_METHOD_ALLOWLIST: &str = "P57: on the left of a WHERE comparison only Length /      IndexOf / Trim* are accepted; any other method fails the query";

const KNOWN_METHODS: &[Known] = &[
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.ToUpper() = 'ABC'",
        observed: "EEEE",
        why: WHERE_METHOD_ALLOWLIST,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.Replace('a', 'z') = 'zbc'",
        observed: "EEEE",
        why: WHERE_METHOD_ALLOWLIST,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "t.s.Contains('b')",
        observed: "TTFT",
        why: NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.Contains('b')",
        observed: "TTFT",
        why: NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.Contains('B')",
        observed: "TTFT",
        why: NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "NOT s.Contains('b')",
        observed: "FFTF",
        why: NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.StartsWith('a')",
        observed: "TTFF",
        why: NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.EndsWith('C')",
        observed: "TTFF",
        why: NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.Length() > 3",
        observed: "FFFT",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.IndexOf('b') = 1",
        observed: "TTFF",
        why: NULL_RECEIVER_AND_WHERE_ALWAYS_NOCASE,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.IndexOf('z') = -1",
        observed: "TTTT",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.Trim() = 'aB'",
        observed: "FFFT",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.TrimStart() = 'aB '",
        observed: "FFFT",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.TrimEnd() = ' aB'",
        observed: "FFFT",
        why: NULL_RECEIVER,
    },
];

const KNOWN_METHODS_CASE_INSENSITIVE: &[Known] = &[
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.Contains('B')",
        observed: "TTFT",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "NOT s.Contains('B')",
        observed: "FFTF",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.StartsWith('A')",
        observed: "TTFF",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.EndsWith('c')",
        observed: "TTFF",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.IndexOf('B') = 1",
        observed: "TTFF",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "s.Trim() = 'AB'",
        observed: "FFFT",
        why: NULL_RECEIVER,
    },
];

const KNOWN_NUMBER_METHODS: &[Known] = &[
    Known {
        evaluator: Evaluator::Where,
        predicate: "n.Contains('5')",
        observed: "TFFT",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "n.StartsWith('1')",
        observed: "FTFF",
        why: NULL_RECEIVER,
    },
    Known {
        evaluator: Evaluator::Where,
        predicate: "n.Length() > 1",
        observed: "FTFT",
        why: NULL_RECEIVER,
    },
];

fn trilean_char(t: Trilean) -> char {
    match t {
        Trilean::True => 'T',
        Trilean::False => 'F',
        Trilean::Unknown => 'U',
    }
}

fn observe_where(table: &DataTable, predicate: &str, case_insensitive: bool) -> String {
    let sql = format!("SELECT * FROM t WHERE {predicate}");
    let statement = Parser::new(&sql)
        .parse()
        .unwrap_or_else(|e| panic!("parse failed for {sql}: {e}"));
    let where_clause = statement.where_clause.expect("expected a WHERE clause");
    let mut evaluator = RecursiveWhereEvaluator::with_case_insensitive(table, case_insensitive);
    (0..table.row_count())
        .map(|row| match evaluator.evaluate(&where_clause, row) {
            Ok(t) => trilean_char(t),
            Err(_) => 'E',
        })
        .collect()
}

fn observe_value(table: &DataTable, predicate: &str, case_insensitive: bool) -> String {
    // Parenthesised, because a bare `SELECT a AND b` does not parse (logged as
    // a parity gap of its own); the parentheses do not change the expression.
    let sql = format!("SELECT ({predicate}) AS v FROM t");
    let statement = Parser::new(&sql)
        .parse()
        .unwrap_or_else(|e| panic!("parse failed for {sql}: {e}"));
    let expr = match statement.select_items.first() {
        Some(SelectItem::Expression { expr, .. }) => expr.clone(),
        other => panic!("expected one expression select item for {sql}, got {other:?}"),
    };
    let mut evaluator = ArithmeticEvaluator::new(table).with_case_insensitive(case_insensitive);
    (0..table.row_count())
        .map(|row| match evaluator.evaluate(&expr, row) {
            Ok(DataValue::Boolean(true)) => 'T',
            Ok(DataValue::Boolean(false)) => 'F',
            Ok(DataValue::Null) => 'U',
            Ok(_) => 'V',
            Err(_) => 'E',
        })
        .collect()
}

#[test]
fn every_predicate_through_both_evaluators() {
    check_matrix(&table(), EXPECTED, KNOWN, false);
}

#[test]
fn every_predicate_through_both_evaluators_case_insensitive() {
    check_matrix(
        &table(),
        EXPECTED_CASE_INSENSITIVE,
        KNOWN_CASE_INSENSITIVE,
        true,
    );
}

#[test]
fn every_operand_reading_through_both_evaluators() {
    check_matrix(&operand_table(), EXPECTED_OPERANDS, KNOWN_OPERANDS, false);
}

#[test]
fn every_like_pattern_through_both_evaluators() {
    check_matrix(&like_table(), EXPECTED_LIKE, KNOWN_LIKE, false);
}

#[test]
fn like_over_a_number_through_both_evaluators() {
    check_matrix(
        &operand_table(),
        EXPECTED_NUMBER_LIKE,
        KNOWN_NUMBER_LIKE,
        false,
    );
}

#[test]
fn every_method_call_through_both_evaluators() {
    check_matrix(&method_table(), EXPECTED_METHODS, KNOWN_METHODS, false);
}

#[test]
fn every_method_call_through_both_evaluators_case_insensitive() {
    check_matrix(
        &method_table(),
        EXPECTED_METHODS_CASE_INSENSITIVE,
        KNOWN_METHODS_CASE_INSENSITIVE,
        true,
    );
}

#[test]
fn method_calls_over_a_number_through_both_evaluators() {
    check_matrix(
        &method_table(),
        EXPECTED_NUMBER_METHODS,
        KNOWN_NUMBER_METHODS,
        false,
    );
}

fn check_matrix(
    t: &DataTable,
    expected_answers: &[(&str, &str)],
    known: &[Known],
    case_insensitive: bool,
) {
    let mut problems = Vec::new();
    let mut matrix = Vec::new();

    for &(predicate, expected) in expected_answers {
        let where_got = observe_where(t, predicate, case_insensitive);
        let value_got = observe_value(t, predicate, case_insensitive);
        matrix.push(format!(
            "{predicate:<44} expected {expected}  where {where_got}  value {value_got}"
        ));

        for (evaluator, got) in [
            (Evaluator::Where, &where_got),
            (Evaluator::Value, &value_got),
        ] {
            let known = known
                .iter()
                .find(|k| k.evaluator == evaluator && k.predicate == predicate);
            match known {
                None if got != expected => problems.push(format!(
                    "UNRECORDED  {evaluator:?} `{predicate}`: expected {expected}, got {got}"
                )),
                Some(k) if k.observed == expected => problems.push(format!(
                    "STALE ENTRY {evaluator:?} `{predicate}`: KNOWN records the correct answer {expected}; remove it"
                )),
                Some(k) if got == expected => problems.push(format!(
                    "FIXED       {evaluator:?} `{predicate}` now agrees ({expected}); remove its KNOWN entry ({})",
                    k.why
                )),
                Some(k) if got != k.observed => problems.push(format!(
                    "CHANGED     {evaluator:?} `{predicate}`: KNOWN records {}, now {got} (expected {expected})",
                    k.observed
                )),
                _ => {}
            }
        }
    }

    // Every KNOWN entry must name a predicate that is still in the matrix.
    for k in known {
        if !expected_answers.iter().any(|(p, _)| *p == k.predicate) {
            problems.push(format!(
                "ORPHAN      {:?} `{}` is in KNOWN but not in EXPECTED",
                k.evaluator, k.predicate
            ));
        }
    }

    assert!(
        problems.is_empty(),
        "\n{}\n\nFull matrix:\n{}\n",
        problems.join("\n"),
        matrix.join("\n")
    );
}

/// Clause-level forms of the case-insensitive rows, run through
/// `QueryEngine::with_case_insensitive(true)`. The matrix above builds each
/// evaluator directly; these catch the engine's own construction sites (SELECT,
/// HAVING, aggregate arguments, WHERE operands), which is where the mode has to
/// be handed in. `(sql, DuckDB answer with s collated NOCASE, what we return
/// if it differs)` - all agree since slice 3b. Rows are `|`-separated, cells
/// `,`-separated.
const CLAUSES_CASE_INSENSITIVE: &[(&str, &str, Option<&str>)] = &[
    (
        "SELECT (s = 'ABC') AS v FROM t",
        "true|false|NULL|true|NULL",
        None,
    ),
    (
        "SELECT s, COUNT(*) AS n FROM t GROUP BY s HAVING s = 'ABC'",
        "abc,2",
        None,
    ),
    (
        // Not COUNT(*): an empty ungrouped aggregate returns no row (P14).
        "SELECT a FROM t WHERE CASE WHEN s = 'ABC' THEN 1 ELSE 0 END = 1",
        "1|1",
        None,
    ),
    (
        "SELECT SUM(CASE WHEN s = 'ABC' THEN 1 ELSE 0 END) AS n FROM t",
        "2",
        None,
    ),
    (
        "SELECT a, SUM(CASE WHEN s = 'ABC' THEN 1 ELSE 0 END) AS n FROM t \
         WHERE a IS NOT NULL GROUP BY a ORDER BY a",
        "1,2|2,0",
        None,
    ),
];

fn render(value: &DataValue) -> String {
    match value {
        DataValue::Null => "NULL".to_string(),
        DataValue::Boolean(b) => b.to_string(),
        DataValue::Integer(i) => i.to_string(),
        DataValue::Float(f) => f.to_string(),
        DataValue::String(s) => s.clone(),
        other => format!("{other:?}"),
    }
}

#[test]
fn clause_level_case_insensitive() {
    let engine = QueryEngine::with_case_insensitive(true);
    let t = Arc::new(table());
    let mut problems = Vec::new();

    for &(sql, expected, observed) in CLAUSES_CASE_INSENSITIVE {
        let got = match engine.execute(Arc::clone(&t), sql) {
            Ok(view) => (0..view.row_count())
                .map(|i| {
                    let row = view.get_row(i).expect("row in range");
                    row.values.iter().map(render).collect::<Vec<_>>().join(",")
                })
                .collect::<Vec<_>>()
                .join("|"),
            Err(e) => format!("ERROR: {e}"),
        };
        match observed {
            None if got != expected => problems.push(format!(
                "UNRECORDED  `{sql}`: expected {expected}, got {got}"
            )),
            Some(_) if got == expected => problems.push(format!(
                "FIXED       `{sql}` now agrees ({expected}); drop its observed answer"
            )),
            Some(o) if got != o => problems.push(format!(
                "CHANGED     `{sql}`: recorded {o}, now {got} (expected {expected})"
            )),
            _ => {}
        }
    }

    assert!(problems.is_empty(), "\n{}\n", problems.join("\n"));
}
