//! R13 slice 1 — the evaluator matrix.
//!
//! The engine has two evaluators for the same expression tree, and they do not
//! share rules (docs/ENGINE_REFACTORING.md § R13):
//!
//! - `RecursiveWhereEvaluator` — predicate → `Trilean`, serves `WHERE`.
//! - `ArithmeticEvaluator` — expression → `DataValue`, serves `SELECT`,
//!   `HAVING`, join conditions and, since P46, WHERE operands.
//!
//! This runs every predicate below through **both**, on every row of a table
//! built so that each operand is NULL somewhere, and compares each answer with
//! the three-valued SQL result. The expected strings were produced by DuckDB
//! (the parity reference), not derived by hand — see `EXPECTED`.
//!
//! The contract is the same as the parity corpus: a divergence is *recorded*,
//! with what we actually return, in `KNOWN`. The test fails if an unrecorded
//! divergence appears **or** if a recorded one changes — including being fixed,
//! so R13 slice 2 has to update this file to prove what it moved.
//!
//! Reading a row string: one character per table row, in row order.
//! `T`/`F`/`U` are TRUE/FALSE/UNKNOWN (NULL); `E` means the evaluator errored,
//! and `V` means the value evaluator returned a non-boolean, non-NULL value.

use sql_cli::data::arithmetic_evaluator::ArithmeticEvaluator;
use sql_cli::data::datatable::{DataColumn, DataRow, DataTable, DataValue};
use sql_cli::data::recursive_where_evaluator::RecursiveWhereEvaluator;
use sql_cli::data::trilean::Trilean;
use sql_cli::sql::parser::ast::SelectItem;
use sql_cli::sql::recursive_parser::Parser;

/// Rows chosen so every binary shape sees a non-NULL pair both ways round, NULL
/// on the left, NULL on the right, and NULL on both.
///
/// | row | a    | b    | s     |
/// |-----|------|------|-------|
/// | 0   | 1    | 2    | 'abc' |
/// | 1   | 2    | 1    | 'xyz' |
/// | 2   | NULL | 1    | NULL  |
/// | 3   | 1    | NULL | 'abc' |
/// | 4   | NULL | NULL | NULL  |
fn table() -> DataTable {
    let mut t = DataTable::new("t");
    t.add_column(DataColumn::new("a"));
    t.add_column(DataColumn::new("b"));
    t.add_column(DataColumn::new("s"));
    let int = |v: Option<i64>| v.map_or(DataValue::Null, DataValue::Integer);
    let text = |v: Option<&str>| v.map_or(DataValue::Null, |s| DataValue::String(s.to_string()));
    for (a, b, s) in [
        (Some(1), Some(2), Some("abc")),
        (Some(2), Some(1), Some("xyz")),
        (None, Some(1), None),
        (Some(1), None, Some("abc")),
        (None, None, None),
    ] {
        t.add_row(DataRow::new(vec![int(a), int(b), text(s)]))
            .unwrap();
    }
    t
}

const ROWS: usize = 5;

/// `(predicate, SQL answer per row)`, generated by DuckDB from the same table:
/// `SELECT CASE WHEN (p) IS NULL THEN 'U' WHEN (p) THEN 'T' ELSE 'F' END`.
const EXPECTED: &[(&str, &str)] = &[
    // Comparisons, with NULL on each side.
    ("a < b", "TFUUU"),
    ("a = b", "FFUUU"),
    ("a <> b", "TTUUU"),
    ("a >= b", "FTUUU"),
    ("a = 1", "TFUTU"),
    ("1 < b", "TFFUU"),
    ("a = NULL", "UUUUU"),
    ("s = 'abc'", "TFUTU"),
    // NULL tests stay two-valued.
    ("a IS NULL", "FFTFT"),
    ("a IS NOT NULL", "TTFTF"),
    // Negation: NOT UNKNOWN is UNKNOWN.
    ("NOT (a < b)", "FTUUU"),
    ("NOT (a = 1)", "FTUFU"),
    // IN / NOT IN, NULL in the probe, in the list, and a column item.
    ("a IN (1, 3)", "TFUTU"),
    ("a IN (1, NULL)", "TUUTU"),
    ("a IN (b, 3)", "FFUUU"),
    ("a NOT IN (3, 4)", "TTUTU"),
    ("a NOT IN (1, NULL)", "FUUFU"),
    ("NOT (a IN (1, 3))", "FTUFU"),
    // BETWEEN, NULL in the value and in either bound.
    ("a BETWEEN 1 AND 5", "TTUTU"),
    ("a BETWEEN 1 AND b", "TFUUU"),
    ("a BETWEEN b AND 5", "FTUUU"),
    ("NOT (a BETWEEN 1 AND b)", "FTUUU"),
    // AND / OR: FALSE dominates AND, TRUE dominates OR, even over UNKNOWN.
    ("a > 0 AND b > 1", "TFFUU"),
    ("a > 1 OR b > 1", "TTUUU"),
    ("a > 5 AND b > 5", "FFFFU"),
    ("a > 5 OR b IS NULL", "FFUTT"),
    ("NOT (a > 0 AND b > 1)", "FTTUU"),
    ("NOT (a > 1 OR b > 1)", "FFUUU"),
    // LIKE.
    ("s LIKE 'a%'", "TFUTU"),
    ("NOT (s LIKE 'a%')", "FTUFU"),
    // Expression operands.
    ("a + 0 < b", "TFUUU"),
    ("a + b > 2", "TTUUU"),
    ("COALESCE(a, 0) < b", "TFTUU"),
    ("NOT (a + 0 < b)", "FTUUU"),
    // CASE: an UNKNOWN condition takes the ELSE branch.
    ("CASE WHEN a < b THEN 1 ELSE 0 END = 1", "TFFFF"),
    ("CASE WHEN a < b THEN true ELSE false END", "TFFFF"),
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Evaluator {
    /// `RecursiveWhereEvaluator`, as `WHERE <predicate>`.
    Where,
    /// `ArithmeticEvaluator`, as `SELECT (<predicate>) AS v`.
    Value,
}

/// A recorded divergence from `EXPECTED`: what this evaluator returns today,
/// and why. Remove an entry when a change makes the evaluator agree.
struct Known {
    evaluator: Evaluator,
    predicate: &'static str,
    observed: &'static str,
    why: &'static str,
}

// Empty since R13 slice 2 (2026-09-13), which made the value evaluator
// three-valued: all 32 value-evaluator entries recorded by slice 1 - comparisons
// (including NULL = NULL comparing equal), NOT, IN / NOT IN, BETWEEN, LIKE and
// AND / OR - went FIXED in one change, and the WHERE column did not move.
// Keep the mechanism: a new predicate that exposes a divergence is recorded
// here, with its finding, rather than left failing.
const KNOWN: &[Known] = &[];

fn trilean_char(t: Trilean) -> char {
    match t {
        Trilean::True => 'T',
        Trilean::False => 'F',
        Trilean::Unknown => 'U',
    }
}

fn observe_where(table: &DataTable, predicate: &str) -> String {
    let sql = format!("SELECT * FROM t WHERE {predicate}");
    let statement = Parser::new(&sql)
        .parse()
        .unwrap_or_else(|e| panic!("parse failed for {sql}: {e}"));
    let where_clause = statement.where_clause.expect("expected a WHERE clause");
    let mut evaluator = RecursiveWhereEvaluator::new(table);
    (0..ROWS)
        .map(|row| match evaluator.evaluate(&where_clause, row) {
            Ok(t) => trilean_char(t),
            Err(_) => 'E',
        })
        .collect()
}

fn observe_value(table: &DataTable, predicate: &str) -> String {
    // Parenthesised, because a bare `SELECT a AND b` does not parse (logged as
    // a parity gap of its own); the parentheses do not change the expression.
    let sql = format!("SELECT ({predicate}) AS v FROM t");
    let statement = Parser::new(&sql)
        .parse()
        .unwrap_or_else(|e| panic!("parse failed for {sql}: {e}"));
    let expr = match statement.select_items.first() {
        Some(SelectItem::Expression { expr, .. }) => expr.clone(),
        other => panic!("expected one expression select item for {sql}, got {other:?}"),
    };
    let mut evaluator = ArithmeticEvaluator::new(table);
    (0..ROWS)
        .map(|row| match evaluator.evaluate(&expr, row) {
            Ok(DataValue::Boolean(true)) => 'T',
            Ok(DataValue::Boolean(false)) => 'F',
            Ok(DataValue::Null) => 'U',
            Ok(_) => 'V',
            Err(_) => 'E',
        })
        .collect()
}

#[test]
fn every_predicate_through_both_evaluators() {
    let t = table();
    let mut problems = Vec::new();
    let mut matrix = Vec::new();

    for &(predicate, expected) in EXPECTED {
        let where_got = observe_where(&t, predicate);
        let value_got = observe_value(&t, predicate);
        matrix.push(format!(
            "{predicate:<44} expected {expected}  where {where_got}  value {value_got}"
        ));

        for (evaluator, got) in [
            (Evaluator::Where, &where_got),
            (Evaluator::Value, &value_got),
        ] {
            let known = KNOWN
                .iter()
                .find(|k| k.evaluator == evaluator && k.predicate == predicate);
            match known {
                None if got != expected => problems.push(format!(
                    "UNRECORDED  {evaluator:?} `{predicate}`: expected {expected}, got {got}"
                )),
                Some(k) if k.observed == expected => problems.push(format!(
                    "STALE ENTRY {evaluator:?} `{predicate}`: KNOWN records the correct answer {expected}; remove it"
                )),
                Some(k) if got == expected => problems.push(format!(
                    "FIXED       {evaluator:?} `{predicate}` now agrees ({expected}); remove its KNOWN entry ({})",
                    k.why
                )),
                Some(k) if got != k.observed => problems.push(format!(
                    "CHANGED     {evaluator:?} `{predicate}`: KNOWN records {}, now {got} (expected {expected})",
                    k.observed
                )),
                _ => {}
            }
        }
    }

    // Every KNOWN entry must name a predicate that is still in the matrix.
    for k in KNOWN {
        if !EXPECTED.iter().any(|(p, _)| *p == k.predicate) {
            problems.push(format!(
                "ORPHAN      {:?} `{}` is in KNOWN but not in EXPECTED",
                k.evaluator, k.predicate
            ));
        }
    }

    assert!(
        problems.is_empty(),
        "\n{}\n\nFull matrix:\n{}\n",
        problems.join("\n"),
        matrix.join("\n")
    );
}
