[package]
name = "sql-cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "sql_cli"
path = "src/lib.rs"

[[bin]]
name = "sql-cli"
path = "src/main.rs"

[dependencies]
reedline = "0.30"
crossterm = { version = "0.28", features = ["use-dev-tty"] }
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1.35", features = ["full"] }
comfy-table = "7.0"
csv = "1.3"
ratatui = "0.29"
tui-input = { version = "0.11", features = ["crossterm"] }
anyhow = "1.0"
regex = "1.0"
fuzzy-matcher = "0.3"
chrono = { version = "0.4", features = ["serde"] }
syntect = "5.0"
tree-sitter = "0.19"
tree-sitter-sql = "0.0.2"
arboard = "3.2"
