#!/bin/bash

VERSION="1.16.0"
echo "# SQL CLI v${VERSION}"
echo ""
echo "**Release Date:** $(date +'%B %d, %Y')"
echo ""
echo "## ✨ What's New"
echo ""
echo "### 🚀 Major Milestone Release"
echo ""
echo "This release completes two major state migrations as part of our ongoing refactoring effort:"
echo ""
echo "- **V26: SortState Migration** - Column sorting now managed centrally in AppStateContainer"
echo "  - Fixed sort cycling (None → Ascending ↑ → Descending ↓ → None)"
echo "  - Resolved infinite recursive loops"
echo "  - Fixed mutable static safety issues"
echo "  - Improved state synchronization"
echo ""
echo "- **V27: CompletionState Migration** - Tab completion now managed centrally"
echo "  - Tab completion for column names and methods"
echo "  - Completion statistics tracking"
echo "  - Context-aware suggestions"
echo "  - Cycle through multiple suggestions with Tab"
echo ""
echo "### 🐛 Bug Fixes"
echo "- Complete V26 SortState migration - resolve all remaining issues"
echo "- Fixed infinite recursive loop in sort_results_data()"
echo "- Fixed mutable static safety issues with fallback_filter_state"
echo "- Fixed double RefCell borrow panic"
echo "- Fixed event handler return values"
echo ""
echo "### 📚 Technical Improvements"
echo "- Centralized state management in AppStateContainer"
echo "- Better encapsulation with dedicated state methods"
echo "- Improved debug logging for state changes"
echo "- Maintains backward compatibility with fallback modes"
echo ""
echo "## 📦 Installation"
echo ""
echo "Download the appropriate binary for your platform from the assets below."
echo ""
echo "### Supported Platforms"
echo "- **Linux x64**: \`sql-cli-linux-x64.tar.gz\`"
echo "- **Windows x64**: \`sql-cli-windows-x64.zip\`"
echo "- **macOS x64** (Intel): \`sql-cli-macos-x64.tar.gz\`"
echo "- **macOS ARM64** (Apple Silicon): \`sql-cli-macos-arm64.tar.gz\`"
echo ""
echo "### Quick Start"
echo "\`\`\`bash"
echo "# Load a CSV file with instant preview"
echo "sql-cli data/customers.csv"
echo ""
echo "# Load JSON data"
echo "sql-cli trades.json"
echo ""
echo "# Connect to API"
echo "sql-cli --url http://localhost:5000"
echo "\`\`\`"