#!/bin/bash

echo "Testing New Action System Key Mappings"
echo "======================================="
echo ""
echo "Test file: test_keys.csv"
echo ""
echo "Keys to test in Results mode:"
echo "  N       - Toggle row numbers (new action)"
echo "  C       - Toggle compact mode (new action)"  
echo "  Ctrl+X  - Export to CSV (new action)"
echo "  Ctrl+J  - Export to JSON (new action)"
echo "  Shift+C - Clear filter (new action, only works if filter is active)"
echo "  F8      - Toggle case insensitive comparisons (new action)"
echo "  F12     - Toggle key press indicator (new action)"
echo ""
echo "Previously migrated actions:"
echo "  p     - Pin column"
echo "  s     - Sort column"
echo "  /     - Column search"
echo "  :     - Jump to row"
echo "  H     - Navigate to viewport top"
echo "  M     - Navigate to viewport middle"
echo "  L     - Navigate to viewport bottom"
echo ""
echo "Run: ./target/release/sql-cli test_keys.csv -e \"select * from data\""
echo ""
echo "Debug mode to see action mapping:"
echo "RUST_LOG=action=info ./target/release/sql-cli test_keys.csv -e \"select * from data\" 2>&1 | grep \"Action system\""