#!/bin/bash

echo "Testing Arrow Key Migration to Action System"
echo "============================================"
echo ""
echo "Test file: test_keys.csv"
echo ""
echo "Keys to test:"
echo "Results mode:"
echo "  ↑     - Navigate up / previous row (bounded at row 0, like vim k)"
echo "  ↓     - Navigate down / next row (like vim j)"
echo "  ←     - Navigate left / previous column (like vim h)" 
echo "  →     - Navigate right / next column (like vim l)"
echo "  Ctrl+F - Page down (vim style)"
echo "  Ctrl+B - Page up (vim style)"
echo ""
echo "Command mode:"
echo "  ↑     - No action (cursor stays in text)"
echo "  ↓     - Switch to Results mode (enter data view)"
echo "  ←     - Move cursor left in query text"
echo "  →     - Move cursor right in query text"
echo ""
echo "Vim navigation keys work identically:"
echo "  h j k l - Same as arrow keys (no mode switching)"
echo ""
echo "Proper vim mode switching (not arrows):"
echo "  i       - Insert mode (switch to Command mode at current position)"  
echo "  a       - Append mode (switch to Command mode at end)"
echo "  A       - Append at end of line"
echo "  Esc     - Exit current mode"
echo ""
echo "Run: ./target/release/sql-cli test_keys.csv -e \"select * from data\""
echo ""
echo "Debug mode to see action system working:"
echo "RUST_LOG=action=info ./target/release/sql-cli test_keys.csv -e \"select * from data\" 2>&1 | grep \"Action system\""